// generated by scripts/bump.sh - do not edit manually

#ifndef version_h
#define version_h

#define APPLICATION_NAME "Lavandula"

#define VERSION_MAJOR    1
#define VERSION_MINOR    0
#define VERSION_PATCH    0

#endif
